// Generated by CoffeeScript 1.3.3
(function() {

  module.exports = function(grunt) {
    return grunt.registerMultiTask("jaded", "compile jaded templates", function() {
      var base, dest, file, files, jaded, templ, _i, _len, _results;
      jaded = require('jaded');
      files = grunt.file.expandFiles(this.file.src);
      grunt.file.mkdir(this.file.dest);
      _results = [];
      for (_i = 0, _len = files.length; _i < _len; _i++) {
        file = files[_i];
        base = path.basename(file, path.extname(file));
        dest = path.join(this.file.dest, "" + base + ".js");
        templ = jaded.compile(grunt.file.read(file), this.data.options);
        _results.push(grunt.file.write(dest, templ));
      }
      return _results;
    });
  };

}).call(this);
